updated KB registry and KB image tag to the latest.
aquasecurity/deployments pull request #570
Opened 2024-08-08 08:15 UTC by mjshastha

updated KB registry and KB image tag to the latest.

2024-08-08 09:42 UTC, deven0t commented on enforcers/kube_enforcer/kubernetes_and_openshift/manifests/kube_enforcer_advanced/003_kube_enforcer_deploy.yaml
> +              value: "registry.aquasec.com/kube-benchv0.7.3:"
colon(:) is misplaced

2024-08-08 11:53 UTC, deven0t approved these changes

2024-08-08 11:56 UTC, mjshastha commented
@semyonmor Can you merge this pr?

2024-10-15 09:56 UTC, yariv-freifeld-aqua approved these changes

2024-12-09 08:35 UTC, seanposner approved these changes

2024-12-09 08:35 UTC, seanposner requested changes
PR is failing

2024-12-10 03:37 UTC, mjshastha commented
@seanposner Can you merge the changes?

2024-12-13 06:06 UTC, mjshastha commented
@seanposner Can you merge the changes?

2024-12-19 06:26 UTC, yariv-freifeld-aqua approved these changes

2024-12-19 06:32 UTC, yariv-freifeld-aqua approved these changes

2024-12-19 06:33 UTC, merged